prefer-workspace-packages: true

packages:
  - packages/*

ignoredBuiltDependencies:
  - '@mattrglobal/node-bbs-signatures'

onlyBuiltDependencies:
  - '@sphereon/pex'
  - '@swc/core'
  - canvas
  - esbuild
  - nx
  - secp256k1
